# Python packages


We do specialized tasks in Python with _packages_. A package is a collection of Python functions that someone wrote and bundled together for you to use. Some of the Python packages that we'll learn to use include: 

| Package | Uses                     |
|---------|--------------------------|
| `numpy` | Math with arrays (more on this below) | 
| `scipy` | A math toolkit built for use by scientists | 
| `matplotlib` | Visualization (plotting!) | 
| `astropy` | Astronomy-specific functions of all kinds | 

## Numpy

Numpy is the most important package that we're going to teach you about, because it allows you to do calculations very quickly with Python. Below, we'll discover why it's useful.

*** 

Let's say you want to take the $\sin$ or $\cos$ of an angle. There are numpy function that do this for you. 

To gain access to numpy's functions, you always need to do this command first: 
```python
import numpy as np
```
Run the line above in the cell below: 

In [1]:
import numpy as np

Now there's a variable called `np` that we can access anywhere in this notebook. There are _functions_ for $\sin$ and $\cos$ that live within numpy. The way to access a function within a package is by calling the function name with a period after it, then the name of the function you want. So for $\sin$, you can do: 
```python
np.sin(0)
```
The `np.` part says "give me this function from numpy". The `sin()` part says "the function that I want to use is $\sin$", and the `0` is the angle that we want to take the $\sin$ of, in units of radians. Run that line in the cell below, and experiment with different angles. Try `np.cos` too.

In [2]:
print(np.sin(0))

0.0


Numpy also has some built-in numbers that you might use. For example, $\pi$ is stored (to high precision!), in `np.pi`. Print out numpy's $\pi$ in the cell below: 

In [19]:
np.pi

3.141592653589793

Now lets say you had a list of angles, like `angles`$= [0, \pi/2, \pi, 3\pi/2, 2\pi]$. You could call `np.sin(angles[0])` to get the $\sin$ of the first angle, then `np.sin(angles[1])` on the second angle, etc. But that would be a really slow way to do it! 

### Arrays

The quick way is to create a _numpy array_. A numpy array is a vector or matrix of numbers which numpy can act on more efficiently than Python can with ordinary lists.

Let's make a numpy array filled with the angles above:
```python
# First, here's the list that we want to have an array of: 
angle_list = [0, 1/2 * np.pi, np.pi, 3/2 * np.pi, 2 * np.pi]

# Here's how we make a numpy array out of the list
angle_array = np.array(angle_list)
```
Write out those lines in the cell below. 

Let's break down the command `np.array(angle_list)`. The `np.` says we're going to use a function from numpy, the `array()` says we're going to make an array out of the thing in the parentheses, and the `angle_list` is the _input_ or the _argument_ of the function. 

Now you can do things with the numpy array that you couldn't do with a Python list. Here are some of them, which you should experiment with in the cell below: 
```python
# Sum of all elements in the array:
angle_array.sum()

# Mean of all elements in the array:
angle_array.mean()

# Maximum of the elements in the array:
angle_array.max()

# Minimum of the elements in the array: 
angle_array.min()
```

In [20]:
angle_list = [0, 1/2 * np.pi, np.pi, 3/2 * np.pi, 2 * np.pi]
angle_array = np.array(angle_list)

print(angle_array.sum())

15.7079632679


### Example 1: Calculations with arrays

What is the $\sin$ and $\cos$ of each angle? Use the numpy array `angle_array` as the argument to the `np.sin` and `np.cos` functions in the cell below:

In [22]:
print(np.sin(angle_array))
print(np.cos(angle_array))

[  0.00000000e+00   1.00000000e+00   1.22464680e-16  -1.00000000e+00
  -2.44929360e-16]
[  1.00000000e+00   6.12323400e-17  -1.00000000e+00  -1.83697020e-16
   1.00000000e+00]


Now you might be saying - wait a minute, $\sin(3\pi/2) = 0$, not $\approx$`1e-16`, what's that about? The short answer is - computers often get very very close to approximating the numbers that we actually want, but not all of the way there. You can get better precision if you tell the computer to use more memory, which we can talk about after class if you like. 

***

## Array arithmetic

There are lots of situations where you'll want to create a certain kind of array, and numpy has functions to help. 

You can make an array of consecutive integers from zero to nine with the function `np.arange`:
```python
consecutive_integers = np.arange(10)
```
If there's one number in the parentheses, it tells `np.arange` what number to stop at (exclusive). If there are three numbers, they signify `np.arange(start, stop, step)`. For example, `np.arange(1, 9, 2)` would start at 1, stop before 9, with a step size of 2, so it would return `[1, 3, 5, 7]`.

In the cell below, make an array with 10,000 sequential integers, starting with the zero. Save the array into a variable called `consecutive_integers`, and print it out:

In [12]:
consecutive_integers = np.arange(10000)
print(consecutive_integers)

[   0    1    2 ..., 9997 9998 9999]


You'll see that numpy is polite. It knows you probably don't want to see all ten thousand integers, so it prints just the beginning and end of the array. 

### Exercise 2: Indexing/slicing numpy arrays
The same indexing and slicing rules that we learned for lists work on arrays. In the cell below, print the 42nd element of the `consecutive_integers` array, and print the 101-103rd (inclusive) elements of the array:

In [14]:
print(consecutive_integers[42])
print(consecutive_integers[101:104])

42
[101 102 103]


Unlike lists, you can do arithmetic with numpy arrays. For example, if you had the following list: 
```python
heights = [162, 185, 174, 191]
```
and you tried to add one to the list, this is what you would get: 
```python
print(heights + 1)
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-23-ca23c21090bd> in <module>()
      1 heights = [162, 185, 174, 191]
----> 2 print(heights + 1)

TypeError: can only concatenate list (not "int") to list
```
However, this does work if `heights` is a numpy array. 

### Exercise 3: Array arithmetic

In the cell below: 
1. Create a variable called `heights_array`, which contains a numpy array of `heights` (using the `np.array` function we learned above)
2. Try adding, multiplying, subtracting, dividing, exponentiating the array

In [24]:
heights = [162, 185, 174, 191]
heights_array = np.array(heights)

print(heights_array + 1)

[163 186 175 192]


### Exercise 4: Inequalities
You can also evaluate inequalities with whole arrays at once. Find which values of the array above are greater than 180: 

In [26]:
heights_array > 180

array([False,  True, False,  True], dtype=bool)

Notice - numpy arrays don't have to contain numbers (floats and integers). They can be booleans, and other things too!

### Exercise 5: Fancy indexing 

We now want to print only the heights in the array that are greater than 180. Given what you know so far, print the heights greater than 180, by accessing them with their indices, i.e. something like 

```python
print(heights_array[<put something in here>])
```

In [27]:
print(heights_array[1], heights[3])

185 191


In Exercise 4, you found that you can figure out which numbers in the array were greater than 180 all at once. It turns out, if you save that array of booleans: 

```python
heights_gt_180 = heights_array > 180
```

You can use `heights_gt_180` like a group of indices on `heights_array` to get just the heights where `heights_gt_180 == True`. 

In the cell below, try:
```python
heights_gt_180 = heights_array > 180
print(heights_array[heights_gt_180])
```
Did it print out the right indices? What if you flip the greater than to a less than? What if you try `==` instead?

In [29]:
heights_gt_180 = heights_array > 180
print(heights_array[heights_gt_180])

[185 191]


## Putting it all together

Using all of these skills together, let's do something that we couldn't do easily with a scientific calculator. Let's find sum of all of the positive, even numbers less than 10,000.

We'll do that in a few steps below: 

In [44]:
# We'll use np.arange to make a list of all numbers between 0 and 10,000
numbers_lt_10000 = np.arange(10000)

# Now we'll find out which of those numbers are even by figuring out
# which ones have a remainder of zero when you divide them by two
remainders = numbers_lt_10000 % 2
print(remainders)

[0 1 0 ..., 1 0 1]


In [45]:
# The even numbers are the ones where the remainders are equal to zero: 
where_even = (remainders == 0)

print(where_even)

[ True False  True ..., False  True False]


In [46]:
# Now if we use where_even to index numbers_lt_10000, 
# we'll get an array of just the even numbers: 
numbers_even = numbers_lt_10000[where_even]

print(numbers_even)

[   0    2    4 ..., 9994 9996 9998]


In [47]:
# Now let's use the sum function to sum up the array above: 
print(numbers_even.sum())

24995000


***

### Exercise 6

Using the above steps as a template, figure out the sum of the **odd** numbers less than **100,000**:

In [48]:
# We'll use np.arange to make a list of all numbers between 0 and 100,000
numbers_lt_100000 = np.arange(100000)

# Now we'll find out which of those numbers are even by figuring out
# which ones have a remainder of *one* when you divide them by two
remainders = numbers_lt_100000 % 2

# The odd numbers are the ones where the remainders are equal to one: 
where_odd = (remainders == 1)

# Now if we use where_even to index numbers_lt_100000, 
# we'll get an array of just the odd numbers: 
numbers_odd = numbers_lt_100000[where_odd]

# Now let's use the sum function to sum up the array above: 
print(numbers_odd.sum())

2500000000
